### PR TITLE
feat: enable aot

### PR DESCRIPTION
**Pull request by pchampio**
The current flutter channel beta doesn't have all the embedding functions needed to compile this go-flutter version.
We advocate user to use the flutter beta channel. So we cannot push flutter master channel specific sutff.

Please merge this PR once theses functions are merged in flutter beta.

### CODE REVIEW

**Comment by jld3103** [comment]
This will be a breaking change for users that don't have hover upgraded whilst having updated go-flutter, because the LDFLAGS are moved to hover.

**Comment by pchampio** [comment]
If we add a buildtag (like https://github.com/go-flutter-desktop/go-flutter/blob/master/internal/opengl/opengl.go#L1) but for ld flags it might enable backward compatibility.
Something like `hover_set_ld_flag` in a new build.go file. and keep those flag for older hover version.

**Comment by jld3103** [comment]
That seems to be a good idea

**Comment by jld3103** [comment]
Backwards compatibility implemented. @pchampio can you merge and tag/release it as `v0.42.0`? Hover with AOT requires that version and checks for it.

**Comment by pchampio** [comment]
Done: https://github.com/go-flutter-desktop/go-flutter/compare/v0.41.2...v0.42.0

**Pull request merged**
