### PR TITLE
Implement system UI Clipboard

### PR DESCRIPTION
**Pull request by pas2k**
This implements support for the UI-backed clipboard interface.

image

### CODE REVIEW

**Comment by Drakirus** [comment]
I am currently crafting a Plugin system #20.
I plan to merge a V1 of the Plugin system this week (Some cleanup still needs to be done).

One #20 is merged, I'll be happy to merge your work!

**Comment by pas2k** [comment]
Sure thing, no rush.

**Comment by Drakirus** [comment]
#20 is merged,
Please refactor the system UI Clipboard to be a [system_plugins](https://github.com/Drakirus/go-flutter-desktop-embedder/blob/master/system_plugins.go).
And add it to the default plugin list [here](https://github.com/Drakirus/go-flutter-desktop-embedder/blob/6e1b3f4a9d33e33ebea3e8a835bdc1d27ae9c985/gutter.go#L23).
Thanks :100:

**Comment by pas2k** [comment]
Got it.

**Pull request closed without merging**
